#!/usr/bin/env python3
"""Generate single-binary agent assets; --check detects stale generated sources."""
import argparse
import base64
import hashlib
import json
from pathlib import Path
import textwrap

repo = Path(__file__).resolve().parents[1]
parser = argparse.ArgumentParser(description=__doc__)
parser.add_argument('--check', action='store_true')
args = parser.parse_args()
skill = (repo / 'skills/sparekey/SKILL.md').read_text()
logo = (repo / 'docs/assets/logo.png').read_bytes()
manifest = json.loads((repo / 'packaging/codex/plugin.json').read_text())
# Content changes must select a fresh Codex cache even when the CLI version is unchanged.
digest = hashlib.sha256(json.dumps(manifest, sort_keys=True).encode() + skill.encode() + logo).hexdigest()[:16]
manifest['version'] = manifest['version'].split('+')[0] + '+codex.' + digest
manifest_text = json.dumps(manifest, indent=2) + '\n'
header = '// Generated by scripts/embed-agent-assets.py. Do not edit by hand.\n'
outputs = {
    'Sources/sparekey/EmbeddedSkill.swift': header + 'enum EmbeddedSkill {\n    static let content = #"""\n' + skill.rstrip('\n') + '\n"""# + "\\n"\n}\n',
    'Sources/sparekey/EmbeddedCodexPlugin.swift': header + '''import Foundation

enum EmbeddedCodexPlugin {
    static let version = "''' + manifest['version'] + '''"
    static let manifest = #"""
''' + manifest_text.rstrip('\n') + '''
"""# + "\\n"
    static let logo = Data(base64Encoded: """
''' + '\n'.join(textwrap.wrap(base64.b64encode(logo).decode(), 100)) + '''
""", options: .ignoreUnknownCharacters)!
}
'''
}
for relative, content in outputs.items():
    path = repo / relative
    if args.check:
        if not path.exists() or path.read_text() != content:
            raise SystemExit(f'Stale generated asset: {relative}; run scripts/embed-agent-assets.py')
    else:
        path.write_text(content)
print('Agent assets are current.' if args.check else 'Generated embedded agent assets.')
